# fly.toml app configuration file generated for largesizewomanshoes on 2025-02-03T14:18:00+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'largesizewomanshoes'
primary_region = 'sin'

[build]
  [build.args]
    GO_VERSION = '1.23.4'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
[[services.ports]]
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[services.static]
    dir = "/usr/local/share/app/statics"
    file_server = true

[[services.checks]]
  http_path = "/"
  interval = "10s"
  timeout = "2s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
